### ISSUE TITLE
Incorrect week numbers 2025/2026

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#11334]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=32985&p=168290#p168290)

Hello,

We use several custom presets where we show the weeknumbers. Most of our customer prefer weeknumbers over dates. According to your documentation if we use dateFormat: "WW" this should show the ISO weeknumbers. However around the end of 2025, start of 2026 this is not the case.

I reproduced this in an example project, React-vite advanced in v6.1.6 of the Gantt. I added the following code to GanttProps:

```
  presets:[
        {
            id: "weekDateAndMonth",
            name: "Weeks 3",
            rowHeight: 24,
            tickWidth: 30,
            tickHeight: 40,
            displayDateFormat: "ll",
            shiftUnit: "week",
            shiftIncrement: 1,
            defaultSpan: 10,
            timeResolution: {
            unit: "day",
            increment: 1,
            },
            headers: [
            {
                increment: 1,
                unit: "month",
                dateFormat: "YYYY MMMM",
            },
            {
                increment: 1,
                unit: "week",
                dateFormat: "WW",
            },
            ],
            mainHeaderLevel: 1,
            columnLinesFor: 1,
        },
    ],
    viewPreset: "weekDateAndMonth",
```

This sets the viewpreset to one that shows weeknumbers. If I then navigate to the end of 2025, I see a week 53. 
![Screenshot 2025-05-13 115301.png](https://forum.bryntum.com/download/file.php?id=34781)

However according to the ISO system(and also for example Outlook), it should go from week 52 to week 1. According to the ISO rule the year of the weeknumber is based on which year thursday falls in. So with thursday being on 1st January 2026, this is week 1. https://en.wikipedia.org/wiki/ISO_week_date

Which should result in:
![Screenshot 2025-05-13 115831.png](https://forum.bryntum.com/download/file.php?id=34782)

So I think this is a bug. Is there an easy way to implement a custom render function to correct this?
![Screenshot 2025-05-13 115301.png](https://forum.bryntum.com/download/file.php?id=34781)
![Screenshot 2025-05-13 115831.png](https://forum.bryntum.com/download/file.php?id=34782)

**Comment by chuckn0rris** [comment]
Related to https://github.com/bryntum/support/issues/10991

**Comment by isglass** [comment]
Should be fixed by the ticket @chuckn0rris refers to above, have asked for confirmation

**Comment by chuckn0rris** [comment]
@isglass user confirmed the issue is still persists. I will set high-prio back on this.

**Comment by JockeLindberg** [comment]
There is another report on the same issue here https://github.com/bryntum/support/issues/12098 which is currently being worked on

**Comment by kronaemmanuel** [comment]
This is not an issue of incorrect week numbers. It's due to not setting the locale or `weekStartDay` properly. Please check discussion here: https://github.com/bryntum/support/issues/12098#issuecomment-3660110398

**Comment by matsbryntse-dev** [comment]
Dupe
