### ISSUE TITLE
Drag drop not finalized if eventStore data is updated during dragging

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1929]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?p=79531&sid=f397b10ba8e1062b8fb0bc8b235d0259#p79531)

http://lh/bryntum-suite/scheduler/examples/dragselection/
Select 'Click me' event
Run snippet below in console
`setTimeout(() => scheduler.events = [], 3000)
`Start dragging the click me event
After data is updated, drop events - note the drop didn't finalize properly as the event was removed
<img width="669" alt="Screenshot 2020-11-22 at 10 08 33" src="https://user-images.githubusercontent.com/218570/99899567-b0f76d80-2caa-11eb-99b5-13613cc026d6.png">
```

Uncaught TypeError: Cannot read property 'resizable' of undefined
    at EventDrag.isElementDraggable (EventDrag.js:248)
    at DragHelper.isElementDraggable (DragBase.js:123)
    at DragHelper.onPointerDown (DragHelper.js:440)
    at DragHelper.onMouseDown (DragHelper.js:508)
    at HTMLDivElement.handler (EventHelper.js:511)

```

Try also same thing illustrating event being updated (replaced)
```

setTimeout(() => scheduler.events = [{
            id         : 1,
            resourceId : 'r1',
            startDate  : new Date(2017, 0, 1, 10),
            endDate    : new Date(2017, 0, 1, 12),
            name       : 'Click me',
            iconCls    : 'b-fa b-fa-mouse-pointer'
        }], 3000)
```

After drag drop, try dragging it again for another crash:
```

Collection.js:1105 Uncaught TypeError: Cannot read property 'id' of undefined
    at Collection.includes (Collection.js:1105)
    at Scheduler.isAssignmentSelected (EventSelection.js:198)
    at EventDrag.setupProductDragData (EventDrag.js:725)
    at EventDrag.getDragData (DragBase.js:659)
    at EventDrag.getDragData (EventDrag.js:757)
    at EventDrag.onDragStart (DragBase.js:233)
    at EventDrag.onDragStart (EventDrag.js:296)
    at DragHelper.trigger (Events.js:1057)
    at DragHelper.callPreventable (Events.js:898)
    at DragHelper.internalMove (DragHelper.js:530)
```

**Comment by cmanoliu** [comment]
Hello Mats, 

Any idea when a fix will be available ? Thank you.

Regards,

Catalin

**Comment by matsbryntse** [comment]
Try using https://bryntum.com/docs/scheduler/#Core/data/mixin/StoreSync#config-syncDataOnLoad to update existing data instead of removing and reinserting? Does this fix your issue?

**Comment by cmanoliu** [comment]
> Try using https://bryntum.com/docs/scheduler/#Core/data/mixin/StoreSync#config-syncDataOnLoad to update existing data instead of removing and reinserting? Does this fix your issue?

Thank you. My team will test the syncDataOnLoad workaround. I will let you know.

**Comment by cmanoliu** [comment]
> Try using https://bryntum.com/docs/scheduler/#Core/data/mixin/StoreSync#config-syncDataOnLoad to update existing data instead of removing and reinserting? Does this fix your issue?

Setting syncDataOnLoad = true does not fix the issue.

**Comment by matsbryntse** [comment]
@cmanoliu Could you please try again using latest release?

**Comment by cmanoliu** [comment]
> @cmanoliu Could you please try again using latest release?

Hello, 

I'm sorry but this issue is not solved at all. We are still reproducing it with your sample and also with our code.

Please reopen the issue and assign it the proper (high) priority. 
**It has become a serious problem for us.**

Thank you for your support.


KO with your sample :
![bug](https://user-images.githubusercontent.com/10958934/107062004-19011e80-67d9-11eb-874f-7a8e98087319.gif)

Also KO in our code (same errors, occurring randomly) :

**Error 1**
![error1](https://user-images.githubusercontent.com/10958934/107063384-9d07d600-67da-11eb-85df-26727bfdf452.PNG)

**Error 2**
![error2](https://user-images.githubusercontent.com/10958934/107063419-a98c2e80-67da-11eb-9435-f80f02b4f552.PNG)

**Comment by matsbryntse** [comment]
Are you using syncDataOnLoad and still see this?

**Comment by matsbryntse** [comment]
Case #1 with event removed while dragging fixed in https://github.com/bryntum/support/issues/2346

**Comment by matsbryntse** [comment]
How do we reproduce error #2, can you please provide a simple test case like above?

**Comment by cmanoliu** [comment]
> Are you using syncDataOnLoad and still see this?

we tested "syncDataOnLoad = true" and the events are not even shown with 4.0.8 (we also tested with with 4.0.7 when events were shown)

![syncDataOnLoad true KO](https://user-images.githubusercontent.com/10958934/107264175-f40fe400-6a42-11eb-9d82-6aa612527a0e.PNG)

**Comment by cmanoliu** [comment]
> How do we reproduce error #2, can you please provide a simple test case like above?

For the "TypeError: cannot read property 'assignments' of undefined" we don't have a simple test case, only production code.

**Comment by cmanoliu** [comment]
> How do we reproduce error #2, can you please provide a simple test case like above?

Hello @matsbryntse, @SergeyMaltsev 

We found how to reproduce the #2 error (cannot read property 'Assignments' of undefined) with the same sample scenario. 
It happens after you select the event immediately after drop with a selection rectangle, see the attached animated gif:

![cannot read property Assignments of undefined](https://user-images.githubusercontent.com/10958934/108100037-abc97500-7085-11eb-9afa-6be3edaeeae4.gif)

Thank you for your support.

**Comment by matsbryntse** [comment]
Thanks for the test case, this is already fixed in our 4.1.0 beta (please try and verify in our nightly builds). 

![delete](https://user-images.githubusercontent.com/218570/108115081-eb9a5780-7099-11eb-96b1-3c6755dbd1b6.gif)

We also built this new stress test injecting tons of changes continuously to verify the Scheduler holds up in a dynamic environment (you can try it too in the nightlies). https://twitter.com/bryntum/status/1360259893278765066

**Comment by cmanoliu** [comment]
Hello Mats (@matsbryntse),

We migrated our code to use the (final) 4.1.0 version of the Scheduler. 

Unfortunatelly, **both errors** **still exist when multiple events** are selected, dragged and then dropped after refreshing the data.

![bryntum bug reproduced with multi-selection drag and drop after refresh](https://user-images.githubusercontent.com/10958934/115230575-d8951980-a114-11eb-8d23-cf2ab58b2366.gif)

The fix included with version 4.1.0 only handles the case when only one event is dropped.

Please reopen the ticket with a high priority assigned.
These errors already taken too long to be fixed and are preventing us from upgrading to the latest version. 

Thank you for your support.

Catalin

**Comment by matsbryntse** [comment]
Thanks for reporting this, we have opened a new issue to fix this: https://github.com/bryntum/support/issues/2774
