### ISSUE TITLE
`UndoRedo` widget doesn't catch the project if configured standalone in Angular

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#3789]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=19553&p=96740#p96740)

Try to add UndoRedo widget standalone (not on scheduler's tbar) in Angular demo with  shared `project`:

```
 <bryntum-undo-redo
        [project]="schedulerConfig.project"
    ></bryntum-undo-redo>
```

in config file
```
    project : new ProjectModel({
        autoLoad   : true,
        transport : {
            load : {
                url : 'assets/data/data.json'
            }
        },
        stm : {
            autoRecord : true
        }
    })
```

It won't catch the project and won't reflect on project's changes. But it should, according to docs.

**Comment by chuckn0rris** [comment]
Please update Angular demo with example of using <bryntum-undo-redo/>

**Comment by chuckn0rris** [comment]
Another request [here](https://forum.bryntum.com/viewtopic.php?f=52&t=23637&p=117013#p117013)

**Comment by jsakalos** [comment]
I have investigated this issue and the source of the error is the wrong type for `project` property in `bryntum-undo-redo.component.d.ts`. The existing type is:

```
export declare class BryntumUndoRedoComponent implements OnInit, OnDestroy {
    // ...
    project: SchedulerProjectModel;
```

when that is changed to:
```
export declare class BryntumUndoRedoComponent implements OnInit, OnDestroy {
    // ...
    project: ProjectModel | object | Partial<ProjectModelConfig>;
```

everything works as expected.

**Comment by NordicLight** [comment]
Great! Is this fix then coming in the next 5.3.1?

**Comment by jsakalos** [comment]
@NordicLight The issue is fixed now and it will be released in the next 5.3.2.

**Comment by taauntik** [comment]
This is still reproducible

It is reproducible with our angular inline-data demo

This is the updated `app.component.html` file
```
<!-- BryntumDemoHeader component is used for Bryntum example styling only and can be removed -->
<bryntum-demo-header></bryntum-demo-header>

<div class = "demo-toolbar align-right">
    <bryntum-button
        text = 'Change data'
        cls = 'b-raised b-blue'
        (onAction) = "onChangeData()"
    ></bryntum-button>
    <!-- added this only ⬇️ -->
    <bryntum-undo-redo
        [project]="project"
    ></bryntum-undo-redo>
    <!-- added this only ⬆️ -->
</div>

<bryntum-project-model
    #project
    [calendar]     = "projectConfig.calendar!"
    [startDate]    = "projectConfig.startDate!"
    [hoursPerDay]  = "projectConfig.hoursPerDay!"
    [daysPerMonth] = "projectConfig.daysPerMonth!"
    [tasks]        = "tasks"
    [timeRanges]   = "timeRanges"
    [assignments]  = "assignments"
    [resources]    = "resources"
    [dependencies] = "dependencies"
    [calendars]    = "calendars"
></bryntum-project-model>
<bryntum-gantt
    [project]           = "project"
    [columnLines]       = "ganttConfig.columnLines!"
    [columns]           = "ganttConfig.columns!"
    [subGridConfigs]    = "ganttConfig.subGridConfigs!"
    [viewPreset]        = "ganttConfig.viewPreset!"
    [timeRangesFeature] = "ganttConfig.features!.timeRanges!"
></bryntum-gantt>

```

**Comment by jsakalos** [comment]
@taauntik & @matsbryntse there are 2 things that cause that:

1. `project` must be defined first (in `app.component.html`), before any other components that use it (it's how Angular works):
```
<bryntum-project-model
    #project
    [events] = "projectData.events"
    [resources] = "projectData.resources"
    [assignments] = "projectData.assignments"
    [dependencies] = "projectData.dependencies"
></bryntum-project-model>
<bryntum-undo-redo
    [project]="project"
></bryntum-undo-redo>
<bryntum-scheduler-pro
    #schedulerpro
    [startDate] = "schedulerProConfig.startDate"
    [endDate] = "schedulerProConfig.endDate"
    [viewPreset] = "schedulerProConfig.viewPreset"
    [forceFit] = "schedulerProConfig.forceFit"
    [columns] = "schedulerProConfig.columns"
    [project] = "project"
></bryntum-scheduler-pro>

```
2. STM must be enable in code:

```
    ngAfterViewInit(): void {
        // SchedulerPro instance
        this.schedulerPro = this.schedulerProComponent.instance;
        this.schedulerPro.project.stm.enable(); // <--- this line
    }
```

then it works:
![undo](https://user-images.githubusercontent.com/204844/234254874-334281a7-1ee8-405f-8634-07a19f9bd215.gif)

**Comment by isglass** [comment]
App issue

**Comment by NordicLight** [comment]
Hi,

Great almost there! Adding your code snippet into our code base it is now working however not for all events. So swapping row orders triggers the undo but e.g. not modifying task name & task start & end date.

Happy to share example code. However looking at your snip-it I see that we are missing below in our "bryntym-project-model" which looks like the problem... Could not find any configuration [event] in the gantt angular examples so could you please share what you are feeding in?

[events] = "projectData.events"

Regards
Johan

**Comment by NordicLight** [comment]
Did find the problem myself! Moving the stm autoRecord from the config to code did the trick 

this.gantt.project.stm.autoRecord = true;
